--- # config.yaml

task: classification
devices: gpu:0


#
# Dataset
#
num_classes: 10
batch_size: 64
num_workers: 4
mixup_alpha: 0.
cutmix_alpha: 0.


#
# Training hyperparameters
#
epochs: 300
init_lr: 1.e-3
seed: 0

optimizer: AdamW
optimizer_cfg:
  weight_decay: 5.e-2

lr_scheduler: CosineAnnealingLR
lr_scheduler_cfg:
  eta_min: 1.e-5

warmup_lr_scheduler: LinearLR
warmup_lr_scheduler_cfg:
  start_factor: 1.e-2
  total_iters: 20

criterion: CrossEntropyLoss
criterion_cfg:
  label_smoothing: 0.


#
# Metrics
#
metrics:
- "acc@1"
- "ce@l1"
- "ce@sign"

track:
# - "feature_rms"
- "grad_l2"
- "param_svdval_max"
- "state_dict"


... # end