--- # config.yaml

devices: gpu:0


num_classes: 10
batch_size: 64
num_workers: 4
seed: 0


#
# Travel
#
travel:
  method: "fgsm"
  init_eps: 1.e-3
  stride: 1.e-3
  stride_decay: 0.5
  tol: 1.e-10
  max_iter: 10000
  turnaround: 0.1


... # end