# https://github.com/pytorch/vision/tree/main/references/classification
--- # config.yaml

devices: gpu:0,1,2,3
seed: 0
amp: true

# -------
# Dataset
# -------
num_classes: 1000
batch_size: 256
num_workers: 8
pin_memory: true

# ---------
# Transform
# ---------
crop_size: 224
resize_size: 256
interpolation: bicubic
hfip_prob: 0.5
auto_augment_policy: ta_wide
ra_magnitude: 9
augmix_severity: 3
random_erase_prob: 0.25
backend: pil

# --------------
# Regularization
# --------------
label_smoothing: 0.1
mixup_alpha: 0.8
cutmix_alpha: 1.0
gradient_clip_val: 5.0

# ------------------------
# Training hyperparameters
# ------------------------
epochs: 300
init_lr: 1.e-3

optimizer: AdamW
optimizer_cfg:
  weight_decay: 5.e-2

lr_scheduler: CosineAnnealingLR
lr_scheduler_cfg:
  eta_min: 1.e-5

warmup_lr_scheduler: LinearLR
warmup_lr_scheduler_cfg:
  start_factor: 1.e-2
  total_iters: 20

criterion: CrossEntropyLoss

... # end