num_classes: 10
batch_size: 128
num_workers: 2

epochs: 200
init_lr: 0.1
seed: 0

optimizer: SGD
optimizer_cfg:
  momentum: 0.9
  weight_decay: 5.e-4

lr_scheduler: MultiStepLR
lr_scheduler_cfg:
  milestones: [ 60, 120, 160, ]
  gamma: 0.2

warmup_lr_scheduler: LinearLR
warmup_lr_scheduler_cfg:
  start_factor: 0.01
  total_iters: 10

criterion: CrossEntropyLoss

metrics:
  acc@1:
    Accuracy:
      task: multiclass
      top_k: 1
  ece:
    CalibrationError:
      task: multiclass
#  mae:
#    MeanAbsoluteError:
#      { }
